name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2

      - name: Assemble
        run: ./gradlew assemble

      - name: Release Package
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew library:publish

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "changelog.config.json"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: |
            ./library/build/libs/library-${{ env.GITHUB_REF_NAME }}.jar
            ./app/build/outputs/apk/debug/app-debug.apk
